version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "django"
        versions: [">=3.0", "<3.2"]  # don't offer to bump django until 3.2 LTS released
