language: python
python:
  - 3.8
install:
  - npm i -g npm
  - npm install
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
  - pip install coveralls
script:
  - python manage.py makemigrations --check
  - npx grunt sass:dist
  - npx grunt postcss:dist
  - npx grunt uglify:scripts
  - git diff --exit-code static/
  - coverage run manage.py test
  - flake8 .
after_success:
  - coveralls
notifications:
  slack:
    secure: D2UrTxFolji0qnKvRMqnearuRqdsu9IAdLzOd3d/jOIVtzc2Nqmzd70s2sWLx4rtX/vKbeqEpz1yf738GR48hZhKIy07ySB/hi7u2TelafPzAmaZ+k0jUzWsfACVKpkF77IjSgQ29orUDNUuac2Hc8Wo+niYS3cqVwRprZKmkrs=
